name: Deployment

on:
  # this job is started after git push on branch "main" or "dev"
  push:
    branches:
      - main
      - dev
  # allow user to start job manually
  workflow_dispatch:

jobs:

  # we define our job, which name is "build"
  build:

    # run job with OS: Linux Ubuntu
    runs-on: ubuntu-latest

    steps:
      
      # get the code from git repository
      - uses: actions/checkout@v3

      # install Java Development Kit version 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # use a specific Dockerfile (deploy/Dockerfile-nginx-front) to build a specific image with a web server (nginx) and compiled front files
      - name: Build FRONT image
        run: docker build -f ./deploy/Dockerfile-nginx-front -t ${{ secrets.DOCKERHUB_USERNAME }}/wns-deploy-angular-spring-front:${GITHUB_REF##*/} .

      # build backend image with Spring Boot plugin for Maven 
      - name: Build BACK image with Maven
        working-directory: ./back
        run: ./mvnw --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/} "-Dimage.dockeruser=${{ secrets.DOCKERHUB_USERNAME }}/"      

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # print generated images
      - name: Display local images
        run: docker images
      
      # deploy front image to Docker Hub (in DOCKERHUB_USERNAME namespace)
      - name: Push FRONT image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wns-deploy-angular-spring-front:${GITHUB_REF##*/}

      # deploy back image to Docker Hub (in DOCKERHUB_USERNAME namespace)
      - name: Push BACK image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wns-deploy-angular-spring-back:${GITHUB_REF##*/}
